name: CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: All Checks 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        name: Build 1
        with:
          command: build
          args: --tests

      - uses: actions-rs/cargo@v1
        name: Run Tests 1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        name: Check formatting 1
        if: ${{ success() || failure() }}
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy 1
        if: ${{ success() || failure() }}
        with:
          command: clippy
          args: --tests -- -D warnings -D clippy::pedantic
